gOtherText_NewName::
    .string "新名字$"

gNameChoice_Green::
    .string "青绿$"

gNameChoice_Red::
    .string "赤红$"

gNameChoice_Leaf::
    .string "小绿$"

gNameChoice_Fire::
    .string "小炎$"

gNameChoice_Gary::
    .string "小刚$"

gNameChoice_Kaz::
    .string "小和$"

gNameChoice_Toru::
    .string "小透$"

gNameChoice_Ash::
    .string "小智$"

gNameChoice_Kene::
    .string "小健$"

gNameChoice_Geki::
    .string "小激$"

gNameChoice_Jak::
    .string "小杰克$"

gNameChoice_Janne::
    .string "小珍妮$"

gNameChoice_Jonn::
    .string "小约翰$"

gNameChoice_Kamon::
    .string "小河童$"

gNameChoice_Karl::
    .string "卡尔$"

gNameChoice_Taylor::
    .string "泰勒$"

gNameChoice_Oscar::
    .string "奥斯卡$"

gNameChoice_Hiro::
    .string "小广$"

gNameChoice_Max::
    .string "麦克斯$"

gNameChoice_Jon::
    .string "乔恩$"

gNameChoice_Ralph::
    .string "拉尔夫$"

gNameChoice_Kay::
    .string "凯伊$"

gNameChoice_Tosh::
    .string "小俊$"

gNameChoice_Roak::
    .string "小罗克$"

gNameChoice_Omi::
    .string "小欧米$"

gNameChoice_Jodi::
    .string "乔迪$"

gNameChoice_Amanda::
    .string "阿曼达$"

gNameChoice_Hillary::
    .string "希拉里$"

gNameChoice_Makey::
    .string "麦基$"

gNameChoice_Michi::
    .string "米奇$"

gNameChoice_Paula::
    .string "宝拉$"

gNameChoice_June::
    .string "琼恩$"

gNameChoice_Cassie::
    .string "卡西$"

gNameChoice_Rey::
    .string "雷伊$"

gNameChoice_Seda::
    .string "塞达$"

gNameChoice_Kiko::
    .string "奇奇$"

gNameChoice_Mina::
    .string "米娜$"

gNameChoice_Norie::
    .string "小野理$"

gNameChoice_Sai::
    .string "小彩$"

gNameChoice_Momo::
    .string "桃子$"

gNameChoice_Suzi::
    .string "苏西$"

gControlsGuide_Text_Intro::
    .string "首先,进行对游戏的操作\n"
    .string "以及所分配的按键的说明.$"

gControlsGuide_Text_DPad::
    .string "用于控制主角的行动.\n"
    .string "也可以用于选择不同的选项.$"

gControlsGuide_Text_AButton::
    .string "用于决定选项,调查物品,\n"
    .string "与NPC聊天以及继续显示对话内容.$"

gControlsGuide_Text_BButton::
    .string "用于退出或者取消选项.\n"
    .string "也用于退出菜单.$"

gControlsGuide_Text_StartButton::
    .string "用于打开菜单.$"

gControlsGuide_Text_SelectButton::
    .string "用于移动或者登录物品\n"
    .string "或使用被登录的物品.$"

gControlsGuide_Text_LRButtons::
    .string "如果在游戏中遇到不明白的地方\n"
    .string "可以按下L或R键打开帮助.$"

gOakSpeech_Text_AskPlayerGender::
    .string "现在告诉我,你是男孩?\n"
    .string "还是女孩?$"

gPikachuIntro_Text_Page1::  
    .string "在这个你即将进入的世界中，\n你将踏上一场宏大的冒险之旅，\n而你就是主角。\n"
    .string "无论你走到哪里，\n都要与人交谈，查看各种事物，\n无论是城镇、道路还是洞穴。\n从每一个信息源收集情报和线索。$"

gPikachuIntro_Text_Page2::  
    .string "通过帮助需要帮助的人，克服挑战，\n解开谜题，新的道路将为你开启。\n"
    .string "有时候，你会被他人挑战，\n也会遭到野生生物的攻击。\n要勇敢，继续前进。$"

gPikachuIntro_Text_Page3::  
    .string "在你的冒险过程中，\n我们希望你能与各种各样的人交流互动，\n实现个人成长。这是我们最大的目标。\n"
    .string "按下A键，开始你的冒险之旅吧！$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "你好啊!\n"
    .string "很高兴见到你!\p"
    .string "欢迎来到宝可梦世界!\p"
    .string "我是大木博士.\p"
    .string "人们公认的\n"
    .string "宝可梦专家.\p$"

gOakSpeech_Text_ThisWorld::
    .string "这个世界…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…遍布着名为\n"
    .string "宝可梦的生物。\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "对一些人来说，宝可梦是宠物。\n"
    .string "还有人用它们来对战。\p"
    .string "而我…\p"
    .string "我是以研究宝可梦为职业。\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "不过首先，先说说\n"
    .string "你自己的事吧。\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "先从名字开始吧。\n"
    .string "你叫什么名字？\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "好的…\n"
    .string "你叫{PLAYER}对吧。$"

gOakSpeech_Text_WhatWasHisName::
    .string "这是我孙子。\p"
    .string "你们从小就是对手。\p"
    .string "……嗯，他叫什么来着？$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "你对手的名字，\n"
    .string "叫什么来着？$"

gOakSpeech_Text_ConfirmRivalName::
    .string "……是叫{RIVAL}吗？$"

gOakSpeech_Text_RememberRivalsName::
    .string "对了！我想起来了！\n"
    .string "他叫{RIVAL}！\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}！\p"
    .string "属于你的宝可梦传说\n"
    .string "即将展开！\p"
    .string "充满梦想和冒险的宝可梦世界\n"
    .string "在等着你！出发吧！$"
